# Generated by Django 3.2.7 on 2021-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisamapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('address2', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
