# Generated by Django 3.2.7 on 2021-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisamapp', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
