# Generated by Django 3.2.7 on 2021-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourisamapp', '0004_news_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='state',
            field=models.CharField(default=45, max_length=50),
            preserve_default=False,
        ),
    ]
